### ISSUE TITLE
get_user_info

### ISSUE THREAD

**Issue by thanhpp** [thanhpp/zola#55]
## Request
- token
- user_id

## Response
- code
- message
- data
  - id
  - username
  - created
  - description - ???
  - avatar
  - cover_image
  - link
  - address
  - city
  - country
  - listing: number of user's friends
  - is_friend:
  - online: 1 - online; 0 - offline

## test cases
- [x] 1000 | OK
- [x] ErrLockedUser => user not exist
- [x] User not exist
- [ ] Blocked => user not exist

## Tasks
- Update the user model
  - avatar and cover_image storage
  - address information
- Online feature?

**Comment by phamthanhhang208** [comment]
missing phonenumber, name and state

**Comment by phamthanhhang208** [comment]
wrong listing number
